# fly.toml app configuration file generated for red-sound-2482 on 2023-05-23T09:12:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app_name = "red-sound-2482"
primary_region = "gru"

[build]
  image = "lucasprzm/datingapp:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dpm78kd1e"
  CloudinarySettings__ApiKey="779596526883276"

  [experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"